---
title: "Coding Challenge 5"
author: "Maryam Saeed Noor Fatima"
date: "2025-03-20"
output:
  word_document: default
  pdf_document: default
  html_document: default
pdf_document:
  toc: true
md_document: null
variant: gfm
---

#### Q.No.1 Adding the csv files

```{r}
library(tidyverse)
library(readr)
library(ggplot2)

diversityData <- read.csv("DiversityData.csv")
metadata <- read.csv("Metadata.csv")
str(diversityData)
str(metadata)
```

#### Q.No.2 Joining the data frame and giving them alpha name

```{r}
left_join(diversityData, metadata, by = "Code")
alpha<- left_join(diversityData, metadata, by = "Code")
head(alpha)
```

#### Q.No.3 Making pielou richness index column using mutate

```{r}
 alpha %>%
  mutate(pielou_eveness = shannon/log(richness))
 
alpha_even<- alpha %>%
  mutate(pielou_eveness = shannon/log(richness))
head(alpha_even)
```

#### Q.No.4 calculating mean and Sd of pielou eveness group

```{r}
alpha_average<-alpha_even %>%
  group_by(Crop, Time_Point)%>%
  summarise(mean_even = mean(pielou_eveness), # calculating mean
            n = n(), # count of observation
            sd_eveness = sd(pielou_eveness)) %>% # standard deviation
            mutate(se_eveness = sd_eveness/sqrt(n)) #standard error
```

#### Q.No.5 Calculating the difference

```{r}


alpha_average2<- alpha_average%>%
  select(Time_Point, Crop, mean_even) %>% # selecting the relevent columns
  pivot_wider(names_from = Crop, values_from = mean_even)%>% # povot wider function 
   mutate(dff.cotton.even = Soil - Cotton, #creating a new column using mutate for calculating difference
          dff.Soybean.even =  Soil - Soybean)
```

#### Q.No.6 Connecting to plots

```{r}
alpha_average2 %>%
  select(Time_Point, dff.cotton.even, dff.Soybean.even)%>%
  pivot_longer(c(dff.cotton.even, dff.Soybean.even),
               names_to = "diff")%>%
  ggplot(aes(x = Time_Point, y = value, colour = diff))+
  geom_line()+
  theme_minimal()+
  xlab("Time Point (hrs)")+
  ylab("Difference from soil in Pielou's eveness" )

```
#### Commit and push code to get clickable link of the pdf


